/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifdef MAGMA_ENABLE_NFS_INTERFACE

#include "nfs_prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
nfs_program_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		nfs_fh nfsproc_getattr_2_arg;
		sattrargs nfsproc_setattr_2_arg;
		diropargs nfsproc_lookup_2_arg;
		nfs_fh nfsproc_readlink_2_arg;
		readargs nfsproc_read_2_arg;
		writeargs nfsproc_write_2_arg;
		createargs nfsproc_create_2_arg;
		diropargs nfsproc_remove_2_arg;
		renameargs nfsproc_rename_2_arg;
		linkargs nfsproc_link_2_arg;
		symlinkargs nfsproc_symlink_2_arg;
		createargs nfsproc_mkdir_2_arg;
		diropargs nfsproc_rmdir_2_arg;
		readdirargs nfsproc_readdir_2_arg;
		nfs_fh nfsproc_statfs_2_arg;
	} argument;
	union {
		attrstat nfsproc_getattr_2_res;
		attrstat nfsproc_setattr_2_res;
		diropres nfsproc_lookup_2_res;
		readlinkres nfsproc_readlink_2_res;
		readres nfsproc_read_2_res;
		attrstat nfsproc_write_2_res;
		diropres nfsproc_create_2_res;
		nfsstat nfsproc_remove_2_res;
		nfsstat nfsproc_rename_2_res;
		nfsstat nfsproc_link_2_res;
		nfsstat nfsproc_symlink_2_res;
		diropres nfsproc_mkdir_2_res;
		nfsstat nfsproc_rmdir_2_res;
		readdirres nfsproc_readdir_2_res;
		statfsres nfsproc_statfs_2_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NFSPROC_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_null_2_svc;
		break;

	case NFSPROC_GETATTR:
		_xdr_argument = (xdrproc_t) xdr_nfs_fh;
		_xdr_result = (xdrproc_t) xdr_attrstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_getattr_2_svc;
		break;

	case NFSPROC_SETATTR:
		_xdr_argument = (xdrproc_t) xdr_sattrargs;
		_xdr_result = (xdrproc_t) xdr_attrstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_setattr_2_svc;
		break;

	case NFSPROC_ROOT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_root_2_svc;
		break;

	case NFSPROC_LOOKUP:
		_xdr_argument = (xdrproc_t) xdr_diropargs;
		_xdr_result = (xdrproc_t) xdr_diropres;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_lookup_2_svc;
		break;

	case NFSPROC_READLINK:
		_xdr_argument = (xdrproc_t) xdr_nfs_fh;
		_xdr_result = (xdrproc_t) xdr_readlinkres;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_readlink_2_svc;
		break;

	case NFSPROC_READ:
		_xdr_argument = (xdrproc_t) xdr_readargs;
		_xdr_result = (xdrproc_t) xdr_readres;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_read_2_svc;
		break;

	case NFSPROC_WRITECACHE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_writecache_2_svc;
		break;

	case NFSPROC_WRITE:
		_xdr_argument = (xdrproc_t) xdr_writeargs;
		_xdr_result = (xdrproc_t) xdr_attrstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_write_2_svc;
		break;

	case NFSPROC_CREATE:
		_xdr_argument = (xdrproc_t) xdr_createargs;
		_xdr_result = (xdrproc_t) xdr_diropres;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_create_2_svc;
		break;

	case NFSPROC_REMOVE:
		_xdr_argument = (xdrproc_t) xdr_diropargs;
		_xdr_result = (xdrproc_t) xdr_nfsstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_remove_2_svc;
		break;

	case NFSPROC_RENAME:
		_xdr_argument = (xdrproc_t) xdr_renameargs;
		_xdr_result = (xdrproc_t) xdr_nfsstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_rename_2_svc;
		break;

	case NFSPROC_LINK:
		_xdr_argument = (xdrproc_t) xdr_linkargs;
		_xdr_result = (xdrproc_t) xdr_nfsstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_link_2_svc;
		break;

	case NFSPROC_SYMLINK:
		_xdr_argument = (xdrproc_t) xdr_symlinkargs;
		_xdr_result = (xdrproc_t) xdr_nfsstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_symlink_2_svc;
		break;

	case NFSPROC_MKDIR:
		_xdr_argument = (xdrproc_t) xdr_createargs;
		_xdr_result = (xdrproc_t) xdr_diropres;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_mkdir_2_svc;
		break;

	case NFSPROC_RMDIR:
		_xdr_argument = (xdrproc_t) xdr_diropargs;
		_xdr_result = (xdrproc_t) xdr_nfsstat;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_rmdir_2_svc;
		break;

	case NFSPROC_READDIR:
		_xdr_argument = (xdrproc_t) xdr_readdirargs;
		_xdr_result = (xdrproc_t) xdr_readdirres;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_readdir_2_svc;
		break;

	case NFSPROC_STATFS:
		_xdr_argument = (xdrproc_t) xdr_nfs_fh;
		_xdr_result = (xdrproc_t) xdr_statfsres;
		local = (bool_t (*) (char *, void *,  struct svc_req *))nfsproc_statfs_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		syslog (LOG_ERR, "%s", "unable to free arguments");
		exit (1);
	}
	if (!nfs_program_2_freeresult (transp, _xdr_result, (caddr_t) &result))
		syslog (LOG_ERR, "%s", "unable to free results");

	return;
}

#endif /* MAGMA_ENABLE_NFS_INTERFACE */
